
services:
  gbsappui:
    build: .
    privileged: true
    container_name: gbsappui_web
    ports:
      - 8111:8090
    volumes:
      - type: bind
        source: /export/prod/public_gbsappui/refgenomes/
        target: /refgenomes
      - type: bind
        source: /export/prod2/gbsappui
        target: /results
      - type: bind
        source: /export/prod/public_gbsappui/scp_uploads/
        target: /scp_uploads/
      - type: bind
        source: /home/production/gbsappui/gbsappui_local.conf
        target: /gbsappui/gbsappui_local.conf
      - type: bind
        source: /home/production/gbsappui/gbsappui.conf
        target: /gbsappui/gbsappui.conf
      - type: bind
        source: /home/production/gbsappui/lib/
        target: /gbsappui/lib
      - type: bind
        source: /home/production/gbsappui/cgroup.conf
        target: /etc/slurm/cgroup.conf
      - type: bind
        source: /home/production/gbsappui/config.sh
        target: /GBSapp/examples/proj/config.sh
      - type: bind
        source: /home/production/gbsappui/mason/
        target: /gbsappui/mason/
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
