
services:
  gbsappui:
<<<<<<< HEAD
    build: .
=======
>>>>>>> 205ae4e (Unmount slurm.conf, temporarily edit refgenome list for cassavabase, and change docker-compose.yml to match vm10)
    image: breedbase/gbsappui:v0.06
    privileged: true
    container_name: gbsappui_web
    ports:
      - 8111:8090
    volumes:
      - type: bind
        source: /home/production/gbsappui/refgenomes
        target: /refgenomes
      - type: bind
        source: /export/prod2/gbsappui
        target: /data
      - type: bind
        source: /home/production/gbsappui/gbsappui_local.conf
        target: /gbsappui/gbsappui_local.conf
      - type: bind
        source: /home/production/gbsappui/gbsappui.conf
        target: /gbsappui/gbsappui.conf
      - type: bind
        source: /home/production/gbsappui/lib/
        target: /gbsappui/lib
      - type: bind
        source: /home/production/gbsappui/cgroup.conf
        target: /etc/slurm/cgroup.conf
      - type: bind
        source: /home/production/gbsappui/config.sh
        target: /GBSapp/examples/proj/config.sh
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
