
services:
  gbsappui:
    build: .
    image: breedbase/gbsappui:v0.06
    privileged: true
    container_name: gbsappui_web
    ports:
      - 8090:8090
    volumes:
      - type: bind
        source: /home/awl/Desktop/genomes
        target: /refgenomes
      - type: bind
        source: /home/awl/breedbase_dockerfile/cxgn/gbsappui/gbsappui_local.conf
        target: /gbsappui/gbsappui_local.conf
      - type: bind
        source: /home/awl/breedbase_dockerfile/cxgn/gbsappui/gbsappui.conf
        target: /gbsappui/gbsappui.conf
      - type: bind
        source: /home/awl/breedbase_dockerfile/cxgn/gbsappui/lib/
        target: /gbsappui/lib
      - type: bind
        source: /home/awl/breedbase_dockerfile/cxgn/gbsappui/slurm.conf
        target: /etc/slurm/slurm.conf
      - type: bind
        source: /home/awl/breedbase_dockerfile/cxgn/gbsappui/cgroup.conf
        target: /etc/slurm/cgroup.conf
      - type: bind
        source: /home/awl/breedbase_dockerfile/cxgn/gbsappui/config.sh
        target: /GBSapp/examples/proj/config.sh
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
